# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{string_masker}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Coleman"]
  s.date = %q{2010-01-13}
  s.description = %q{Takes a string and a hash of parameters and masks the given parameters from appearing in the string.}
  s.email = %q{progressions@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/string_masker.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/string_masker_spec.rb",
     "string_masker.gemspec"
  ]
  s.homepage = %q{http://github.com/progressions/string_masker}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Masks parameters in a string}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/string_masker_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.6"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.6"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.6"])
  end
end

